# Generated by Django 4.1.2 on 2022-11-20 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dev_club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devdue',
            name='ammount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devdue',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devpayment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DevMember',
        ),
    ]
