# Generated by Django 4.1.2 on 2022-11-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_club', '0002_alter_devdue_ammount_alter_devdue_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devdue',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
