# Generated by Django 4.1.2 on 2022-10-28 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro_club', '0004_alter_event_event_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Due',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField()),
                ('date', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_club.member')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_club.payment')),
            ],
        ),
    ]
