# Generated by Django 4.1.2 on 2022-11-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_club', '0008_payment_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='due',
            name='ammount',
            field=models.IntegerField(default=0),
        ),
    ]
