# Generated by Django 4.1.2 on 2022-11-15 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro_club', '0009_alter_due_ammount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='due',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_club.member'),
        ),
    ]
