# Generated by Django 4.1.2 on 2022-11-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_club', '0010_alter_due_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='due',
        ),
    ]
