# Generated by Django 4.1.2 on 2022-11-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_club', '0011_remove_payment_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='due',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
