# Generated by Django 4.1.2 on 2022-11-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='club_name',
            field=models.CharField(blank=True, choices=[('PROGRAMMING', 'PROGRAMMING'), ('DEVELOPMENT', 'DEVELOPMENT')], max_length=15, null=True),
        ),
    ]
