# Generated by Django 4.1.2 on 2022-11-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('STAFF', 'STAFF'), ('MEMBERS', 'MEMBERS')], default='MEMBERS', max_length=10),
        ),
    ]
