# Generated by Django 4.1.2 on 2022-11-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_alter_customuser_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('STAFF', 'STAFF'), ('MEMBERS', 'MEMBERS'), ('GUEST', 'GUEST')], default='MEMBERS', max_length=10),
        ),
    ]
