# Generated by Django 4.1.2 on 2022-11-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0007_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/assets/img/club.png', null=True, upload_to='user_profile/'),
        ),
    ]
