# Generated by Django 4.1.2 on 2022-11-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0013_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('STAFF', 'STAFF'), ('MEMBERS', 'MEMBERS')], default='MEMBERS', max_length=10),
        ),
    ]
