# Generated by Django 4.1.2 on 2022-11-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='more_image',
            field=models.FileField(blank=True, null=True, upload_to='award_image/more_image/'),
        ),
    ]
