# Generated by Django 4.1.2 on 2022-11-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_award_more_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
