# Generated by Django 4.1.2 on 2022-11-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0007_remove_comment_project_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
