# Generated by Django 4.1.2 on 2022-11-20 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0009_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='more_image',
        ),
        migrations.CreateModel(
            name='AwardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='award_image/')),
                ('award', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.award')),
            ],
        ),
    ]
